<div class="slide" id="slide12" data-slide="12">
    <div class="wrapper">
    
    <article class="bigtext">
        <p>For the Ecuadorian economy, Yasuní is more important for the dollars that rise up from its grounds than for the life forms it shelters. According to data from Ecuador’s Central Bank, in 2012, the four active plots in Yasuní produced 32 million barrels of oil, 17.4% of the total of 184 million barrels produced by the entire country that year.</p>

        <p>According to Eugenio Pappalardo, oil concession areas represent almost 75% of the total area of the Yasuní Biosphere Reserve and include parts of Waorani territory. Only the intangible zone is free from oil drilling activities.</p>

        <p>Contained in the Biosphere Reserve, it is thought that the underground of Yasuní National Park holds 895 million barrels only in ITT fields (43) and in plot 31. According to a 2010 survey, this corresponds to 12.3% of the country’s verified reserves of 7.3 billion barrels.</p>

        <div class="video">
            <iframe src="//player.vimeo.com/video/83767214?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff" width="800" height="343" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>

        <p>The exploitation of oil in Yasuní unleashes fierce criticisms. Ecuador’s Constitution says extraction activities must not take place within protected areas. It also establishes that present and future generations have a right to the conservation and restoration of nature. According to Ricardo Crespo, former advisor for Ecuador’s National Council Biodiversity Commission, the problem is that the same Constitution also contains article 407 where the expression “of national interest” can be read. This article allows the President to request from the National Council a declaration that oil, ore or wood exploitation is of national interest even if within protected areas.</p>
        
        <div class="video">
            <iframe src="//player.vimeo.com/video/83624381?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff" width="800" height="343" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>

        <p>In 2013, President Rafael Correa used article 407 to allow oil exploitation in ITT fields (plot 43). This was done although the government itself, from 2007 to 2013, promoted the need to respect indigenous groups living in isolation and avoid oil drilling. The country’s National Council complied with the President’s request.</p>
        
        <p>The same “green constitution”, as it has already been called, prioritizes cultures, communities, indigenous nations and isolated peoples through an acknowledgement of international instruments for protecting populations contained in article 57 of the United Nation’s Declaration on the Rights of Indigenous Peoples. For this reason, the Ecuadorian Constitution should guarantee the collective rights of indigenous communities and of the peoples living in voluntary isolation, such as the Tagaeri and the Taromenane groups that live inside Yasuní National Park.</p>

        <div class="bigimage"><img style="width:800px;" src="img/via_auca/petroleo.jpg" alt="Photo by Martín Bustamante / www.biographica.com.ec">
        <p class="legend"><i>Photo by Martín Bustamante / www.biographica.com.ec</i></p>
        </div>

        <p>Human rights activists and the environmentalist movement put up a fight, but not to keep Yasuní forests untouched, for they have lost this status long ago. The struggle is to defend the biodiversity of these forests and the way of life of its native populations.</p>

        <p>An essential part of this quest is to harmonize indigenous people’s rights, whether living in isolation or not, with the activities around Yasuní.</p>

        <p>Yasuní was and will always be a territory of utopias. It springs forth questions on how to avoid the ethnocide of ancestral cultures, distribute the riches generated by the extraction of its natural resources, while preserving nature. In other words, a classic case of having your cake and eating it too. The region’s future depends on practical and functional answers to these questions.</p>
    </article>

    <article class="textbox">    
        <h2>Oil Data</h2>

        <p>The production of 3 active plots within the national park totaled some 32 million MDBP, 17.4% of current national production, a figure that is not precise because it includes plot 15 whose largest area lies outside Yasuní.</p>

        <iframe src="//e.infogr.am/yasuni_en_01-6051" width="700" height="1257" scrolling="no" frameborder="0" style="border:none;"></iframe>

        <p>The oil sector drove Ecuador’s economic growth for many years. Its participation in the country’s GNP (Gross National Product) has remained stable between 9% and 13%.</p>

        <iframe src="//e.infogr.am/yasuni_en_02-9164" width="700" height="665" scrolling="no" frameborder="0" style="border:none;"></iframe>

        <p>Oil revenues represent a third of the Ecuadorian government’s budget. In 2012, its budget was of US$18.9 billion dollars, of which 32% (US$6 billion) came from oil production.</p>

        <iframe src="//e.infogr.am/yasuni_en_03-9284" width="700" height="639" scrolling="no" frameborder="0" style="border:none;"></iframe>
    </article>

</div>

    <span class="slideno">Yasuní</span>

</div><!--End Slide 12 -->

<script type="text/javascript">
    $(document).ready(function() {
    $trigger = $('#en-slide13'),
    opts = {
        offset: '100%'
    };
 
    $('#en-slide13').waypoint(function(event, direction) {
        $trigger.waypoint('destroy');
        $.get('yasuni-en13.php', function(data) {
            $('#container').append(data);
            $trigger.waypoint(opts);
        });
    }, opts);
});
</script>

<div id="en-slide13"></div>

